#!/usr/bin/env bash
#
# EzboAI — Hostinger KVM VPS One-Command Setup
# Ubuntu 24.04 LTS
#
# Usage (run as root, first login):
#   bash <(curl -fsSL https://raw.githubusercontent.com/YOUR_USER/ezboai/main/infrastructure/vps-setup.sh)
# OR after git clone:
#   sudo bash infrastructure/vps-setup.sh
#
set -euo pipefail

# ============================================================
# CONFIG (edit these before running)
# ============================================================
APP_USER="ezbo"
APP_DIR="/var/www/ezboai"
DOMAIN="ezboai.com"
DB_NAME="ezboai"
DB_USER="ezbouser"
SSH_PORT="2222"
NODE_VERSION="20"

# Generate strong random secrets
DB_PASSWORD="$(openssl rand -base64 32 | tr -d '/+=' | head -c 32)"
APP_ENCRYPTION_KEY="$(openssl rand -hex 32)"
SESSION_SECRET="$(openssl rand -hex 32)"
ADMIN_PASSWORD_DEFAULT="$(openssl rand -base64 16 | tr -d '/+=' | head -c 16)"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m'

log()  { echo -e "${GREEN}[✓]${NC} $1"; }
warn() { echo -e "${YELLOW}[!]${NC} $1"; }
err()  { echo -e "${RED}[✗]${NC} $1"; }
step() { echo -e "\n${BLUE}━━━ $1 ━━━${NC}"; }

if [[ $EUID -ne 0 ]]; then
   err "Eta root user diye chalate hobe. Try: sudo bash $0"
   exit 1
fi

step "1/10 System Update"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get upgrade -y -qq
apt-get install -y -qq \
  curl wget git ufw fail2ban htop nano \
  build-essential ca-certificates gnupg lsb-release \
  unzip zip software-properties-common
log "System updated"

step "2/10 App User Banano (${APP_USER})"
if id "$APP_USER" &>/dev/null; then
  warn "User '$APP_USER' already exists, skipping"
else
  adduser --disabled-password --gecos "" "$APP_USER"
  usermod -aG sudo "$APP_USER"
  log "User '$APP_USER' created"
fi

step "3/10 SSH Hardening (port ${SSH_PORT})"
SSHD_CONFIG="/etc/ssh/sshd_config"
cp "$SSHD_CONFIG" "${SSHD_CONFIG}.bak.$(date +%s)"
sed -i "s/^#\?Port .*/Port ${SSH_PORT}/" "$SSHD_CONFIG"
sed -i "s/^#\?PermitRootLogin .*/PermitRootLogin no/" "$SSHD_CONFIG"
sed -i "s/^#\?PasswordAuthentication .*/PasswordAuthentication yes/" "$SSHD_CONFIG"
sed -i "s/^#\?MaxAuthTries .*/MaxAuthTries 3/" "$SSHD_CONFIG"
systemctl restart ssh || systemctl restart sshd
log "SSH harden — port: ${SSH_PORT}, root login: disabled"

step "4/10 Firewall (UFW)"
ufw --force reset >/dev/null
ufw default deny incoming
ufw default allow outgoing
ufw allow ${SSH_PORT}/tcp comment 'SSH'
ufw allow 80/tcp comment 'HTTP'
ufw allow 443/tcp comment 'HTTPS'
ufw --force enable
log "Firewall enabled"

step "5/10 Fail2ban"
systemctl enable fail2ban >/dev/null 2>&1
systemctl start fail2ban
log "Fail2ban running"

step "6/10 Node.js ${NODE_VERSION} + pnpm + PM2"
curl -fsSL https://deb.nodesource.com/setup_${NODE_VERSION}.x | bash - >/dev/null
apt-get install -y -qq nodejs
npm install -g pnpm pm2 >/dev/null 2>&1
log "Node $(node -v) | pnpm $(pnpm -v) | pm2 $(pm2 -v)"

step "7/10 PostgreSQL 16"
apt-get install -y -qq postgresql postgresql-contrib
systemctl enable postgresql >/dev/null 2>&1
systemctl start postgresql
sudo -u postgres psql <<EOF
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${DB_USER}') THEN
    CREATE USER ${DB_USER} WITH ENCRYPTED PASSWORD '${DB_PASSWORD}';
  END IF;
END
\$\$;
SELECT 'CREATE DATABASE ${DB_NAME} OWNER ${DB_USER}'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${DB_NAME}')\gexec
GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} TO ${DB_USER};
EOF
log "PostgreSQL ready (db: ${DB_NAME}, user: ${DB_USER})"

step "8/10 Nginx + Certbot"
apt-get install -y -qq nginx certbot python3-certbot-nginx
systemctl enable nginx >/dev/null 2>&1
systemctl start nginx
log "Nginx + Certbot installed"

step "9/10 Playwright + Redis Dependencies"
apt-get install -y -qq \
  libnss3 libnspr4 libatk1.0-0 libatk-bridge2.0-0 libcups2 \
  libdrm2 libxkbcommon0 libxcomposite1 libxdamage1 libxfixes3 \
  libxrandr2 libgbm1 libpango-1.0-0 libcairo2 libasound2t64 \
  redis-server
systemctl enable redis-server >/dev/null 2>&1
systemctl start redis-server
log "Playwright deps + Redis installed"

step "10/10 App Directory + Env File"
mkdir -p "$APP_DIR"
chown -R "$APP_USER:$APP_USER" "$APP_DIR"

ENV_FILE="${APP_DIR}/.env.production"
cat > "$ENV_FILE" <<EOF
# EzboAI Production Environment
# Generated by vps-setup.sh on $(date)

NODE_ENV=production
PORT=3001
BASE_PATH=/

# Database
DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@localhost:5432/${DB_NAME}

# Security (DO NOT change after first deploy — encrypted data depends on this)
APP_ENCRYPTION_KEY=${APP_ENCRYPTION_KEY}
SESSION_SECRET=${SESSION_SECRET}

# Admin Panel (CHANGE THIS after first login)
ADMIN_PASSWORD=${ADMIN_PASSWORD_DEFAULT}

# Redis (queue/cache)
REDIS_URL=redis://localhost:6379

# Optional: Web Push (Phase 8 e generate korben)
# VAPID_PUBLIC_KEY=
# VAPID_PRIVATE_KEY=
EOF
chown "$APP_USER:$APP_USER" "$ENV_FILE"
chmod 600 "$ENV_FILE"

# Save credentials summary in root home
CRED_FILE="/root/ezboai-credentials.txt"
cat > "$CRED_FILE" <<EOF
═══════════════════════════════════════════════════════════
  EzboAI VPS Setup — IMPORTANT CREDENTIALS
  Generated: $(date)
  Domain: ${DOMAIN}
═══════════════════════════════════════════════════════════

🔐 SSH Access (root login disabled):
   ssh -p ${SSH_PORT} ${APP_USER}@$(curl -s ifconfig.me)

🐘 PostgreSQL:
   Database: ${DB_NAME}
   User:     ${DB_USER}
   Password: ${DB_PASSWORD}
   URL:      postgresql://${DB_USER}:${DB_PASSWORD}@localhost:5432/${DB_NAME}

🔑 App Secrets (saved to ${ENV_FILE}):
   APP_ENCRYPTION_KEY:  ${APP_ENCRYPTION_KEY}
   SESSION_SECRET:      ${SESSION_SECRET}
   ADMIN_PASSWORD:      ${ADMIN_PASSWORD_DEFAULT}

⚠️  IMPORTANT:
  1. Eii file ekhuni download kore secure jaygay rakhen
     (e.g., scp -P ${SSH_PORT} ${APP_USER}@VPS_IP:${CRED_FILE} ./)
  2. Tarpor server theke delete korun: rm ${CRED_FILE}
  3. Admin password first login er por change korben
  4. ${APP_USER} user er password set korte: passwd ${APP_USER}

📂 App directory: ${APP_DIR}
🔥 Firewall ports open: ${SSH_PORT} (SSH), 80 (HTTP), 443 (HTTPS)

═══════════════════════════════════════════════════════════
EOF
chmod 600 "$CRED_FILE"

# Set ezbo user password to a known value so user can SSH
echo "${APP_USER}:${DB_PASSWORD}" | chpasswd
log "Set '${APP_USER}' password same as DB password (change with: passwd ${APP_USER})"

echo ""
echo -e "${GREEN}╔══════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║  ✓ EzboAI VPS Setup COMPLETE                             ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${YELLOW}NEXT STEPS:${NC}"
echo ""
echo "  1. Credentials dekhun:"
echo "     cat ${CRED_FILE}"
echo ""
echo "  2. Download credentials to your laptop (laptop theke run korun):"
echo "     scp -P ${SSH_PORT} ${APP_USER}@$(curl -s ifconfig.me 2>/dev/null || echo 'YOUR_VPS_IP'):${CRED_FILE} ./ezboai-credentials.txt"
echo ""
echo "  3. Domain DNS point korun ${DOMAIN} → $(curl -s ifconfig.me 2>/dev/null || echo 'this VPS IP')"
echo ""
echo "  4. DNS propagate hole (5-30 min) clone korun:"
echo "     sudo -u ${APP_USER} git clone YOUR_GITHUB_REPO ${APP_DIR}"
echo "     cd ${APP_DIR}"
echo "     sudo bash infrastructure/deploy.sh"
echo ""
echo "  5. SSL setup:"
echo "     sudo certbot --nginx -d ${DOMAIN} -d www.${DOMAIN}"
echo ""
echo -e "${RED}⚠  Eii server reboot dorkar SSH port change er jonno!${NC}"
echo "     sudo reboot"
echo ""
